In [13]:
import numpy as np

A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

multi_array = np.dot(A, B)
print(multi_array)

max = multi_array.max()
print(max)

[[ 5  6  7  8]
 [17 22 27 32]
 [29 38 47 56]]
56
